version: "3"

services:
  traefik:
    image: "traefik:v2.0.0"
    container_name: "traefik"
    restart: "unless-stopped"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api
      #- --api.insecure
      #- --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      #- --certificatesresolvers.leresolver.acme.email=$EMAIL
      #- --certificatesresolvers.leresolver.acme.storage=/acme.json
      #- --certificatesresolvers.leresolver.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/data/traefik/acme.json:/acme.json"
    labels:
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`traefik.estysdesu.tk`)"
      - "traefik.docker.network=traefik_network"
    #  - "traefik.http.routers.traefik.service=api@internal"
    #  - "traefik.http.routers.traefik.tls.certresolver=leresolver"
    #  - "traefik.http.routers.traefik.entrypoints=websecure"
    #  - "traefik.http.routers.traefik.middlewares=authtraefik"
    #  - "traefik.http.middlewares.authtraefik.basicauth.users=user:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/" # user/password
    #  # global redirect to https
    #  - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
    #  - "traefik.http.routers.http-catchall.entrypoints=web"
    #  - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
    #  # middleware redirect
    #  - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  #nextcloud-db:
  #        container_name: nextcloud-db
  #        image: mariadb:10.3.12
  #        restart: unless-stopped
  #        volumes:
  #                - /data/nextcloud-db:/var/lib/mysql
  #        environment:
  #                MYSQL_DATABASE: nextcloud
  #                MYSQL_ROOT_PASSWORD: ${PASSWORD1}
  #                MYSQL_USER: admin
  #                MYSQL_PASSWORD: ${PASSWORD2}
  #        nextcloud:
  #        depends_on:
  #                - nextcloud-db
  #                - traefik
  #        container_name: nextcloud
  #        image: nextcloud:15.0.2
  #        restart: unless-stopped
  #        volumes:
  #                - /data/nextcloud:/var/www/html
  #                - /data/nextcloud/config:/var/www/html/config
  #                - /data/nextcloud/custom_apps:/var/www/html/custom_apps
  #                - /data/nextcloud/data:/var/www/data
  #        environment:
  #                NEXTCLOUD_ADMIN_USER: admin
  #                NEXTCLOUD_ADMIN_PASSWORD: ${PASSWORD3}
  #                NEXTCLOUD_DATA_DIR: /var/www/data
  #                VIRTUAL_HOST: ${DOMAIN_NAME}
  #                LETSENCRYPT_HOST: ${DOMAIN_NAME}
  #                LETSENCRYPT_EMAIL: ${EMAIL}
  #                MYSQL_DATABASE: nextcloud
  #                MYSQL_USER: admin
  #                MYSQL_PASSWORD: ${PASSWORD2}
  #                MYSQL_HOST: nextcloud-db
